name: Node.js CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - run: docker build -t  .
    - run: docker run -p 8080:8080 -d <your username>/node-web-app
    - run: docker ps
